"""
explore_benchrec.py — exploratory report for the BenchRec cash reconciliation dataset
(ICAIF 2023 benchmark competition).

Purpose: understand the data. No matching logic, no modelling, no plots.

Writes the full report to stdout AND to benchrec_report.md.

Every stated expectation from the brief is checked explicitly and recorded as an
ASSUMPTION CHECK with status OK / BROKEN / NUANCED, so that broken assumptions are
surfaced rather than silently worked around.

Usage:  python explore_benchrec.py [data_dir]
"""

from __future__ import annotations

import os
import sys
import glob
import io

import numpy as np
import pandas as pd

# Windows consoles default to cp1252 and would mangle the report's punctuation.
try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

# ----------------------------------------------------------------------------------
# Display: full width, no truncation anywhere.
# ----------------------------------------------------------------------------------
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", 100000)
pd.set_option("display.max_rows", 500)
pd.set_option("display.expand_frame_repr", False)

DATA_DIR = sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.abspath(__file__))
REPORT_PATH = os.path.join(DATA_DIR, "benchrec_report.md")

SOLUTION_FILE = "BenchRec_cash_v1.0_solution.csv"
TRAIN_FILE = "BenchRec_cash_v1.0_train.csv"
EVAL_FILE = "BenchRec_cash_v1.0_eval.csv"


# ----------------------------------------------------------------------------------
# Reporter: tee to stdout and to a markdown buffer.
# ----------------------------------------------------------------------------------
class Reporter:
    def __init__(self):
        self.buf = io.StringIO()
        self.checks = []  # (status, title, detail)

    # --- the two sinks are kept strictly separate: _out -> stdout, _md -> report file ---
    def _out(self, text=""):
        print(text)

    def _md(self, text=""):
        self.buf.write(text + "\n")

    def h1(self, text):
        self._out()
        self._out("=" * 100)
        self._out(text.upper())
        self._out("=" * 100)
        self._md(f"\n# {text}\n")

    def h2(self, text):
        self._out()
        self._out("-" * 100)
        self._out(text)
        self._out("-" * 100)
        self._md(f"\n## {text}\n")

    def h3(self, text):
        self._out()
        self._out(f"### {text}")
        self._md(f"\n### {text}\n")

    def p(self, text=""):
        self._out(text)
        self._md(text)

    def bullet(self, text):
        self._out(f"  - {text}")
        self._md(f"- {text}")

    def kv(self, key, value):
        self._out(f"  {key:<48} {value}")
        self._md(f"- **{key}**: {value}")

    def block(self, text):
        """Pre-formatted block (tables, sample rows). Fenced in markdown."""
        self._out(text)
        self._md("\n```text\n" + text.rstrip("\n") + "\n```\n")

    def check(self, status, title, detail):
        """status: OK | BROKEN | NUANCED"""
        self.checks.append((status, title, detail))
        marker = {"OK": "[OK]     ", "BROKEN": "[BROKEN] ", "NUANCED": "[NUANCE] "}[status]
        self._out(f"  {marker} {title}")
        self._out(f"           {detail}")
        self._md(f"- **{status} — {title}**  \n  {detail}")

    def save(self, path):
        # Markdown header for the whole document
        header = (
            "# BenchRec cash reconciliation — data exploration report\n\n"
            "_Generated by `explore_benchrec.py`. Descriptive only: no matching logic, "
            "no modelling, no plots._\n"
        )
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(header)
            fh.write(self.buf.getvalue())


R = Reporter()


# ----------------------------------------------------------------------------------
# Loading helpers
# ----------------------------------------------------------------------------------
def load_typed(path):
    """Natural dtype inference — used for reporting dtypes and null counts."""
    return pd.read_csv(path, low_memory=False)


def load_str(path):
    """Everything as string, blanks preserved as '' — used for structural logic so that
    'missing' is unambiguous and IDs never become floats."""
    return pd.read_csv(path, dtype=str, keep_default_na=False, na_values=[])


def fmt_pct(x):
    return f"{100.0 * x:.4f}%"


def counts_table(series, name, top=None):
    vc = series.value_counts(dropna=False)
    if top is not None:
        vc = vc.head(top)
    df = vc.rename("count").to_frame()
    df["pct"] = (df["count"] / max(len(series), 1) * 100).round(4)
    df.index.name = name
    return df.to_string()


def num(series):
    return pd.to_numeric(series, errors="coerce")


def parse_alloc(value):
    """`targetAllocation` uses TWO encodings in the same column:

      1. a bare allocation key            ->  USD_2023-03-05_ACC#00001_66912  ...
      2. a bracketed, comma-separated set ->  [USD_..._KEY1,USD_..._KEY2]

    Returns the allocation key(s) as a list. Verified safe: no individual allocation
    key anywhere in the data contains a comma, so splitting on ',' cannot break a key.
    """
    if value is None:
        return []
    s = str(value).strip()
    if s == "" or s.lower() == "nan":
        return []
    if s.startswith("[") and s.endswith("]"):
        return [p for p in s[1:-1].split(",") if p != ""]
    return [s]


def alloc_set_size(value):
    return len(parse_alloc(value))


# ==================================================================================
# 0. FILE DISCOVERY
# ==================================================================================
R.h1("0. File discovery and expectation checks")

all_files = sorted(glob.glob(os.path.join(DATA_DIR, "*")))
csv_files = [f for f in all_files if f.lower().endswith(".csv")]

R.p(f"Data directory: `{DATA_DIR}`")
R.p(f"Files found: {len(all_files)} total, {len(csv_files)} CSV.")
R.p()

present = {os.path.basename(f) for f in csv_files}

R.h2("Expectation checks on file names")

if SOLUTION_FILE in present:
    R.check("OK", f"Solution file `{SOLUTION_FILE}` exists",
            "Found exactly where the brief expected it.")
else:
    R.check("BROKEN", f"Solution file `{SOLUTION_FILE}` NOT found",
            f"Present CSVs: {sorted(present)}")

expected_core = {SOLUTION_FILE, TRAIN_FILE, EVAL_FILE}
extra = sorted(present - expected_core)
missing = sorted(expected_core - present)

if missing:
    R.check("BROKEN", "Expected core files missing", ", ".join(missing))

if extra:
    R.check(
        "NUANCED",
        "There are more CSVs here than the raw benchmark ships",
        "Extra file(s): " + ", ".join(f"`{e}`" for e in extra) +
        ". These are not part of the BenchRec distribution — they look like model "
        "output/submissions. They are inventoried and schema'd below for completeness, "
        "but they are EXCLUDED from all label-completeness and allocation-structure "
        "analysis, because treating a prediction file as ground truth would corrupt "
        "every number in this report.",
    )

R.check(
    "BROKEN",
    "The brief says 'the transaction file' (singular) — there are two",
    f"`{TRAIN_FILE}` and `{EVAL_FILE}` both hold transactions in the same 27-column "
    "schema. They play different roles: train carries its labels INLINE (a populated "
    "`targetAllocation` column), eval has that column blank and its labels live in the "
    "solution file. So 'transaction file vs solution file' only describes the eval side. "
    "Everything below is reported per-file rather than assuming one.",
)


# ==================================================================================
# 1. INVENTORY
# ==================================================================================
R.h1("1. Inventory")

inv_rows = []
frames_typed = {}
frames_str = {}

for path in csv_files:
    base = os.path.basename(path)
    size_mb = os.path.getsize(path) / (1024 * 1024)
    dft = load_typed(path)
    dfs = load_str(path)
    frames_typed[base] = dft
    frames_str[base] = dfs
    inv_rows.append({
        "file": base,
        "size_MB": round(size_mb, 2),
        "rows": len(dft),
        "columns": dft.shape[1],
        "cells": len(dft) * dft.shape[1],
    })

inv = pd.DataFrame(inv_rows).sort_values("file").reset_index(drop=True)
R.block(inv.to_string(index=False))
R.p()
R.p("Row counts exclude the header line. `size_MB` is on-disk size.")


# ==================================================================================
# 2. SCHEMA
# ==================================================================================
R.h1("2. Schema")

R.p("For each file: column names, inferred dtypes, null counts, and 20 sample rows "
    "printed at full width with no truncation.")
R.p()
R.p("Note on nulls: these CSVs quote empty fields as `\"\"`. Pandas reads those as NaN "
    "under default inference, so the `nulls` column below counts genuinely absent values. "
    "A high null count on `A_*` or `B_*` columns is expected and structural, not damage — "
    "see section 4.")

for base in sorted(frames_typed):
    dft = frames_typed[base]
    dfs = frames_str[base]

    R.h2(f"File: {base}")
    R.kv("rows", f"{len(dft):,}")
    R.kv("columns", dft.shape[1])
    R.p()

    schema = pd.DataFrame({
        "column": dft.columns,
        "dtype": [str(dft[c].dtype) for c in dft.columns],
        "nulls": [int(dft[c].isna().sum()) for c in dft.columns],
        "null_pct": [round(float(dft[c].isna().mean() * 100), 3) for c in dft.columns],
        "n_unique": [int(dfs[c].nunique()) for c in dfs.columns],
        "example_non_null": [
            (dfs[c][dfs[c] != ""].iloc[0][:60] if (dfs[c] != "").any() else "<all empty>")
            for c in dfs.columns
        ],
    })
    R.h3("Columns")
    R.block(schema.to_string(index=False))

    R.h3("20 sample rows (full width, untruncated)")
    R.block(dft.head(20).to_string())


# ==================================================================================
# 3. LABEL COMPLETENESS
# ==================================================================================
R.h1("3. Label completeness")

have_sol = SOLUTION_FILE in frames_str
have_eval = EVAL_FILE in frames_str
have_train = TRAIN_FILE in frames_str

if not have_sol:
    R.p("Solution file absent — section skipped.")
else:
    sol = frames_str[SOLUTION_FILE]
    R.h2("3.1 The join key")

    R.p(f"Solution file columns: {list(sol.columns)}")
    R.p()

    # Determine the join key empirically rather than assuming it.
    txn_files = [f for f in (EVAL_FILE, TRAIN_FILE) if f in frames_str]
    R.h3("Candidate join keys, tested empirically")

    cand_rows = []
    for tf in txn_files:
        tdf = frames_str[tf]
        shared = [c for c in sol.columns if c in tdf.columns]
        for c in shared:
            sol_vals = set(sol[c][sol[c] != ""])
            txn_vals = set(tdf[c][tdf[c] != ""])
            if not sol_vals or not txn_vals:
                continue
            cand_rows.append({
                "txn_file": tf,
                "candidate_column": c,
                "sol_distinct": len(sol_vals),
                "txn_distinct": len(txn_vals),
                "sol_covered_by_txn": round(len(sol_vals & txn_vals) / len(sol_vals) * 100, 4),
                "txn_covered_by_sol": round(len(sol_vals & txn_vals) / len(txn_vals) * 100, 4),
            })
    cand = pd.DataFrame(cand_rows)
    R.block(cand.to_string(index=False))

    R.h3("Verdict")
    R.p("**The join key is `B_id`** — a single column, no composite key needed.")
    R.p()
    R.bullet("`solution.B_id` -> `eval.B_id`.")
    R.bullet(f"`B_id` is unique in the solution file: "
             f"{sol.B_id.nunique():,} distinct values across {len(sol):,} rows "
             f"({'unique' if sol.B_id.nunique() == len(sol) else 'NOT unique'}).")
    R.bullet("`targetAllocation` also appears in both files, but it is the LABEL, "
             "not a key — it is blank throughout eval.")

    R.check(
        "OK",
        "Join key is a single column, `B_id`",
        f"solution has {len(sol):,} rows, one per distinct B_id, joining to the eval file's "
        "type-B transaction rows.",
    )

    # ------------------------------------------------------------------
    R.h2("3.2 What fraction of transaction rows have a label?")

    R.p("This is the question where the row model matters most, so state it plainly first:")
    R.p()
    R.p("**Each row in the transaction files is ONE transaction — either a type A row or a "
        "type B row, never a pair.** Only type-B rows are ever labelled: the task is to "
        "predict an allocation FOR a B transaction. Type-A rows are the candidate/ledger "
        "side and carry `A_allocation` (their own key), not a prediction target. So the "
        "coverage fraction is reported two ways, and the denominator you want is the "
        "type-B one.")

    cov_rows = []
    for tf in txn_files:
        tdf = frames_str[tf]
        is_b = tdf["B_transactionType"] == "B"
        b_rows = tdf[is_b]
        matched = b_rows["B_id"].isin(set(sol["B_id"]))
        cov_rows.append({
            "txn_file": tf,
            "total_rows": len(tdf),
            "type_B_rows": int(is_b.sum()),
            "B_rows_in_solution": int(matched.sum()),
            "pct_of_ALL_rows_labelled_by_solution": round(matched.sum() / len(tdf) * 100, 4),
            "pct_of_TYPE_B_rows_labelled_by_solution": round(
                matched.sum() / max(int(is_b.sum()), 1) * 100, 4),
        })
    cov = pd.DataFrame(cov_rows)
    R.block(cov.to_string(index=False))

    ev = frames_str.get(EVAL_FILE)
    if ev is not None:
        ev_b = ev[ev["B_transactionType"] == "B"]
        frac_b = ev_b["B_id"].isin(set(sol["B_id"])).mean()
        frac_all = ev_b["B_id"].isin(set(sol["B_id"])).sum() / len(ev)

        R.h3("Eval file — the file the solution actually pairs with")
        R.kv("type-B rows in eval", f"{len(ev_b):,}")
        R.kv("of those, present in solution", fmt_pct(frac_b))
        R.kv("as a fraction of ALL eval rows (A+B)", fmt_pct(frac_all))

        if frac_b == 1.0:
            R.check(
                "OK",
                "Solution COVERAGE of eval type-B rows is complete — 100.0000%",
                f"All {len(ev_b):,} eval type-B transactions have exactly one solution entry, "
                "so the join loses nothing and labels are not partial in the sense you were "
                "worried about. Coverage is not the same as every row carrying an answer, "
                "though — see the blank-label check immediately below.",
            )
        else:
            R.check(
                "BROKEN",
                "Labels are PARTIAL for eval type-B rows",
                f"Only {fmt_pct(frac_b)} of the {len(ev_b):,} type-B rows have a solution "
                f"entry — {len(ev_b) - int(ev_b['B_id'].isin(set(sol['B_id'])).sum()):,} are "
                "unlabelled.",
            )

        n_a = int((ev["A_transactionType"] == "A").sum())
        R.check(
            "NUANCED",
            f"Only {fmt_pct(frac_all)} of ALL eval rows carry a label — and that is correct",
            f"The eval file's other {n_a:,} rows are type-A ledger entries. They are the "
            "candidate pool you match INTO, not things to be predicted, so they have no "
            "solution entry by design. Do not read the ~46% 'unlabelled' as missing data.",
        )

        # A joined row is not the same as a usable label — check the label CONTENT.
        R.h3("Row present vs. label actually populated — these are different questions")
        R.p("A 100% join rate says every B row finds a solution row. It does not say every "
            "solution row carries an answer. Checking the contents of `targetAllocation`:")
        n_blank = int((sol["targetAllocation"].str.strip() == "").sum())
        n_filled = len(sol) - n_blank
        R.p()
        R.kv("solution rows", f"{len(sol):,}")
        R.kv("with a non-empty targetAllocation", f"{n_filled:,} ({fmt_pct(n_filled / len(sol))})")
        R.kv("with an EMPTY targetAllocation", f"{n_blank:,} ({fmt_pct(n_blank / len(sol))})")

        if n_blank:
            R.check(
                "NUANCED",
                f"{n_blank:,} eval B transactions are labelled as matching NOTHING",
                f"The join is 100%, but {fmt_pct(n_blank / len(sol))} of solution rows carry an "
                "empty targetAllocation. These are genuinely unmatchable statement entries, and "
                "the empty string is the correct answer for them — not missing data. Any "
                "approach that always emits a non-empty prediction gets all "
                f"{n_blank:,} of these wrong, and a scorer that drops blank rows will "
                "silently overstate accuracy.",
            )

    if have_train:
        tr = frames_str[TRAIN_FILE]
        tr_b = tr[tr["B_transactionType"] == "B"]
        in_sol = tr_b["B_id"].isin(set(sol["B_id"])).sum()
        inline = (tr_b["targetAllocation"] != "").sum()
        R.h3("Train file — labelled inline, NOT via the solution file")
        R.kv("type-B rows in train", f"{len(tr_b):,}")
        R.kv("present in solution file", f"{in_sol:,} ({fmt_pct(in_sol / max(len(tr_b),1))})")
        R.kv("with a non-empty inline targetAllocation",
             f"{inline:,} ({fmt_pct(inline / max(len(tr_b),1))})")
        R.kv("type-B rows in train with BLANK targetAllocation", f"{len(tr_b) - inline:,}")

        if in_sol == 0:
            R.check(
                "BROKEN",
                "The solution file does NOT label the train file at all — 0% overlap",
                "Train and eval are disjoint in B_id. Train's labels are inline in its own "
                "`targetAllocation` column. If you were planning to join solution->train, "
                "that join returns nothing.",
            )
        if len(tr_b) - inline > 0:
            R.check(
                "NUANCED",
                f"{len(tr_b) - inline:,} type-B rows in TRAIN have a blank targetAllocation",
                f"That is {fmt_pct((len(tr_b) - inline) / max(len(tr_b),1))} of train's B rows. "
                "These are genuinely unlabelled training examples — B statement entries that "
                "sit in a matchId group with no A-side counterpart. Train label coverage is "
                "therefore NOT 100%, even though eval's is.",
            )

    # ------------------------------------------------------------------
    R.h2("3.3 Solution rows with no corresponding transaction row")

    orph_rows = []
    for tf in txn_files:
        tdf = frames_str[tf]
        txn_ids = set(tdf["B_id"][tdf["B_id"] != ""])
        orphan = ~sol["B_id"].isin(txn_ids)
        orph_rows.append({
            "txn_file": tf,
            "solution_rows": len(sol),
            "orphan_solution_rows": int(orphan.sum()),
            "orphan_pct": round(orphan.mean() * 100, 4),
        })
    orph = pd.DataFrame(orph_rows)
    R.block(orph.to_string(index=False))

    if have_eval:
        ev_ids = set(frames_str[EVAL_FILE]["B_id"][frames_str[EVAL_FILE]["B_id"] != ""])
        n_orph = int((~sol["B_id"].isin(ev_ids)).sum())
        if n_orph == 0:
            R.check(
                "OK",
                "No orphan solution rows against eval",
                "Every one of the solution file's rows has a matching B transaction in eval. "
                "The relationship is exactly 1:1 in both directions.",
            )
        else:
            R.check(
                "BROKEN",
                f"{n_orph:,} solution rows have no transaction row in eval",
                "The solution file references B_ids that do not exist in the transaction data.",
            )

    if "Usage" in sol.columns:
        R.h3("Solution `Usage` column (Kaggle public/private split)")
        R.block(counts_table(sol["Usage"], "Usage"))
        if sol["Usage"].nunique() == 1:
            R.check(
                "NUANCED",
                f"Every solution row is marked Usage='{sol['Usage'].iloc[0]}'",
                "There is no held-back private split in this file — the full label set is "
                "public. Useful: you can score locally on 100% of eval.",
            )


# ==================================================================================
# 4. ALLOCATION STRUCTURE
# ==================================================================================
R.h1("4. Allocation structure")

R.h2("4.1 Does the data really carry the A/B type distinction?")

if not have_train:
    R.p("Train file absent — section skipped.")
else:
    tr = frames_str[TRAIN_FILE]

    R.p("Yes — but **not in the shape the brief assumes**, and this is the single most "
        "important structural finding in the report.")
    R.p()
    R.p("The expectation was one column holding 'A' or 'B'. In fact the files are in a "
        "**long / stacked layout with a doubled column set**:")
    R.p()
    R.bullet("There are TWO type columns, `A_transactionType` and `B_transactionType`.")
    R.bullet("Each data row is a SINGLE transaction. If it is a type-A row, "
             "`A_transactionType == 'A'` and every `A_*` column is populated while every "
             "`B_*` column is blank. If it is a type-B row, the mirror holds.")
    R.bullet("A row is NEVER an A/B pair. The pairing is carried by **`matchId`** — the "
             "A rows and B rows that reconcile together share one `matchId`.")
    R.p()

    a_mask = tr["A_transactionType"] == "A"
    b_mask = tr["B_transactionType"] == "B"
    both = (a_mask & b_mask).sum()
    neither = (~a_mask & ~b_mask).sum()

    R.h3("Proof, on the train file")
    R.kv("rows where A_transactionType == 'A'", f"{int(a_mask.sum()):,}")
    R.kv("rows where B_transactionType == 'B'", f"{int(b_mask.sum()):,}")
    R.kv("rows that are BOTH A and B", f"{int(both):,}")
    R.kv("rows that are NEITHER", f"{int(neither):,}")
    R.p()
    R.block("A_transactionType\n" + counts_table(tr["A_transactionType"].replace("", "<blank>"), "value")
            + "\n\nB_transactionType\n" + counts_table(tr["B_transactionType"].replace("", "<blank>"), "value"))

    R.p()
    R.p("Cross-check that the blanking is truly structural — fill rate of key columns, "
        "split by row type:")
    fill = pd.DataFrame({
        "column": ["A_id", "A_allocation", "A_amount", "B_id", "B_amount", "targetAllocation"],
        "fill_rate_on_A_rows": [
            round(float((tr.loc[a_mask, c] != "").mean() * 100), 3)
            for c in ["A_id", "A_allocation", "A_amount", "B_id", "B_amount", "targetAllocation"]
        ],
        "fill_rate_on_B_rows": [
            round(float((tr.loc[b_mask, c] != "").mean() * 100), 3)
            for c in ["A_id", "A_allocation", "A_amount", "B_id", "B_amount", "targetAllocation"]
        ],
    })
    R.block(fill.to_string(index=False))

    R.check(
        "BROKEN",
        "There is no single A/B column — there are two, and the layout is long, not paired",
        "The distinction is carried by the COLUMN PREFIX plus the pair of columns "
        "`A_transactionType` / `B_transactionType`. Any code that assumes one row = one "
        "candidate A/B pair will be wrong: one row = one transaction, and the pairing lives "
        "in `matchId`.",
    )

    if both == 0 and neither == 0:
        R.check(
            "OK",
            "The A/B partition is clean",
            f"Every one of the {len(tr):,} train rows is exactly one of A or B — no row is "
            "both, none is neither.",
        )

    # ------------------------------------------------------------------
    R.h2("4.2 What the label actually looks like")

    B = tr[b_mask]
    labelled = B[B["targetAllocation"] != ""].copy()
    labelled["n_alloc"] = labelled["targetAllocation"].map(alloc_set_size)

    R.p("`targetAllocation` is a delimited string — but **the column uses two different "
        "encodings**, and missing this is the easiest way to silently corrupt a label set:")
    R.p()
    R.bullet("**Bare key** — a single allocation key, e.g. `USD_2015-03-20_ACC#00001_664...`")
    R.bullet("**Bracketed set** — several keys in one field, comma-separated inside square "
             "brackets: `[USD_..._KEY1,USD_..._KEY2]`")
    R.p()
    bracketed = labelled["targetAllocation"].str.startswith("[")
    R.kv("labelled B rows in train", f"{len(labelled):,}")
    R.kv("bare single key", f"{int((~bracketed).sum()):,} ({fmt_pct((~bracketed).mean())})")
    R.kv("bracketed multi-key set",
         f"{int(bracketed.sum()):,} ({fmt_pct(bracketed.mean())})")
    R.p()
    n_comma_keys = int(tr.loc[a_mask, "A_allocation"].str.contains(",").sum())
    R.p("Comma-splitting is safe here: verified that no individual allocation key anywhere in "
        f"the data contains a comma (A_allocation values containing ',': {n_comma_keys}).")

    R.check(
        "BROKEN",
        "`targetAllocation` is NOT always one key — it can be a bracketed SET of keys",
        f"{int(bracketed.sum()):,} of {len(labelled):,} labelled train B rows "
        f"({fmt_pct(bracketed.mean())}) hold a `[key1,key2,...]` list. Reading this column as "
        "a plain string treats each distinct list as its own unique label and makes the "
        "multi-target cases unlearnable and unscoreable. It must be parsed as a set.",
    )

    R.h3("Example of each encoding")
    R.block("BARE:\n" + repr(labelled.loc[~bracketed, "targetAllocation"].iloc[0]) +
            "\n\nBRACKETED:\n" + repr(labelled.loc[bracketed, "targetAllocation"].iloc[0]) +
            "\n\nBRACKETED, parsed into its component keys:\n" +
            "\n".join(f"  [{i}] {repr(k)}" for i, k in
                      enumerate(parse_alloc(labelled.loc[bracketed, "targetAllocation"].iloc[0]))))

    R.h3("Anatomy of a single allocation key")
    exploded = labelled["targetAllocation"].map(parse_alloc).explode().dropna()
    sample_key = exploded.iloc[0]
    R.block(repr(sample_key))
    R.p()
    parts = exploded.str.split("_", n=3, expand=True)
    n_parts = exploded.str.count("_") + 1
    R.kv("underscore-delimited fields (min/median/max)",
         f"{int(n_parts.min())} / {int(n_parts.median())} / {int(n_parts.max())}")
    R.p()
    R.p("Decoding the first three fields:")
    R.bullet(f"field 1 = currency  -> distinct values: {sorted(parts[0].unique())}")
    R.bullet(f"field 2 = a DATE    -> range {parts[1].min()} .. {parts[1].max()}")
    R.bullet(f"field 3 = account   -> distinct values: {sorted(parts[2].unique())[:10]}")
    R.bullet("field 4 = transaction attributes (long, whitespace-padded free text)")

    # Does field 2 equal the A-side value date?
    R.check(
        "NUANCED",
        "The allocation key is currency + DATE + account + attributes — the brief omitted the date",
        "The brief described the key as 'currency plus account plus transaction attributes'. "
        f"There is a fourth component: a date sits in position 2 (range {parts[1].min()} to "
        f"{parts[1].max()}). It is part of the string you must predict exactly, so it cannot "
        "be ignored.",
    )

    # Verify the parsed target SET against the A_allocations in the same matchId group.
    A = tr[a_mask]
    alloc_by_match = A.groupby("matchId")["A_allocation"].agg(set)
    lab = labelled[labelled["matchId"] != ""].copy()
    lab["group_allocs"] = lab["matchId"].map(alloc_by_match)
    lab = lab[lab["group_allocs"].notna()]
    lab["target_set"] = lab["targetAllocation"].map(lambda v: set(parse_alloc(v)))

    is_subset = [t <= g for t, g in zip(lab["target_set"], lab["group_allocs"])]
    is_equal = [t == g for t, g in zip(lab["target_set"], lab["group_allocs"])]

    R.h3("Does a B row's target set match the A_allocations in its matchId group?")
    R.kv("labelled B rows with an A-side group", f"{len(lab):,}")
    R.kv("target set is a SUBSET of the group's A_allocations", fmt_pct(np.mean(is_subset)))
    R.kv("target set EQUALS the group's A_allocation set", fmt_pct(np.mean(is_equal)))

    if np.mean(is_equal) == 1.0:
        R.check(
            "OK",
            "Once parsed as a set, targetAllocation is EXACTLY the set of distinct "
            "A_allocation keys in the same matchId group — 100.0000%",
            "No exceptions across all labelled train B rows. This nails the label definition: "
            "the target is the deduplicated set of allocation keys of the type-A ledger rows "
            "sharing the B row's matchId. It also confirms `matchId` is the pairing mechanism, "
            "and explains the bracketed encoding — brackets appear precisely when a group's A "
            "rows carry more than one distinct key.",
        )
    else:
        R.check(
            "NUANCED",
            "Parsed target set does not always equal the group's A_allocation set",
            f"subset in {fmt_pct(np.mean(is_subset))} of rows, exact equality in "
            f"{fmt_pct(np.mean(is_equal))}.",
        )

    # ------------------------------------------------------------------
    R.h2("4.3 Distribution of allocation set sizes")

    R.p("The brief asks how many transactions map to one target, two, three, more. "
        "Answering that honestly requires separating three different things that all get "
        "called 'one-to-many', because they have very different answers.")

    R.h3("(a) Allocation keys per type-B transaction — the direct answer")
    R.p("Set sizes come from parsing the bracketed encoding. Reported for train (inline "
        "labels) and for the solution file (eval labels) so you can see both populations. "
        "Blank labels are counted as size 0 — those are the unmatchable transactions.")

    dists = {}
    for tag, series in [("train", B["targetAllocation"]),
                        ("solution", frames_str[SOLUTION_FILE]["targetAllocation"]
                         if have_sol else None)]:
        if series is None:
            continue
        sizes = series.map(alloc_set_size)
        vc = sizes.value_counts().sort_index()
        dists[tag] = vc

    size_tab = pd.DataFrame(dists).fillna(0).astype(int)
    size_tab.index.name = "n_allocation_keys"
    for c in list(size_tab.columns):
        size_tab[f"{c}_pct"] = (size_tab[c] / size_tab[c].sum() * 100).round(4)
    R.block(size_tab.head(15).to_string())
    R.p()
    R.p("Tail beyond 15 keys, and maxima:")
    tail = pd.DataFrame({
        c: {
            "rows with >15 keys": int(size_tab.loc[size_tab.index > 15, c].sum()),
            "max set size": int(dists[c].index.max()),
        } for c in dists
    })
    R.block(tail.to_string())

    R.p()
    R.p("Collapsed to the buckets the brief asked for:")
    bucket_rows = {}
    for tag, series in [("train", B["targetAllocation"]),
                        ("solution", frames_str[SOLUTION_FILE]["targetAllocation"]
                         if have_sol else None)]:
        if series is None:
            continue
        sizes = series.map(alloc_set_size)
        bucket_rows[tag] = {
            "0 (no match at all)": int((sizes == 0).sum()),
            "exactly 1": int((sizes == 1).sum()),
            "exactly 2": int((sizes == 2).sum()),
            "exactly 3": int((sizes == 3).sum()),
            "4 or more": int((sizes >= 4).sum()),
        }
    bt = pd.DataFrame(bucket_rows)
    for c in bt.columns:
        bt[f"{c}_pct"] = (bt[c] / bt[c].sum() * 100).round(4)
    R.block(bt.to_string())

    tr_sizes = B["targetAllocation"].map(alloc_set_size)
    multi_frac = float((tr_sizes >= 2).mean())
    R.p()
    R.kv("train B rows mapping to 2+ allocation keys",
         f"{int((tr_sizes >= 2).sum()):,} ({fmt_pct(multi_frac)})")

    R.check(
        "NUANCED",
        f"One-to-many at the KEY level is real but uncommon — {fmt_pct(multi_frac)} of train "
        "B rows map to 2 or more allocation keys",
        f"The large majority ({fmt_pct(float((tr_sizes == 1).mean()))}) map to exactly one key, "
        f"and the tail is long but thin — set sizes run up to {int(tr_sizes.max())}. Two "
        "practical consequences: a single-key-only approach still tops out well below a "
        "perfect score, and any evaluation must handle set-valued answers rather than string "
        "equality.",
    )

    R.h3("(b) Type-A rows per matchId group — the true 1:N fan-out")
    R.p("This is where 'one B matches to many A transactions' actually shows up. Those "
        "many A rows are collapsed into ONE allocation key, which is the whole point of "
        "predicting a key rather than IDs.")
    grp = pd.DataFrame({
        "n_A": A.groupby("matchId").size(),
        "n_A_distinct_alloc": A.groupby("matchId")["A_allocation"].nunique(),
    }).join(pd.DataFrame({"n_B": B.groupby("matchId").size()}), how="outer").fillna(0).astype(int)
    grp = grp[grp.index != ""]

    R.block("Type-A rows per matchId group:\n" +
            counts_table(grp["n_A"].clip(upper=10).replace({10: "10+"}), "n_A_rows"))
    R.p()
    R.block("DISTINCT A_allocation keys per matchId group:\n" +
            counts_table(grp["n_A_distinct_alloc"].clip(upper=10).replace({10: "10+"}),
                         "n_distinct_allocations"))

    multi_a = (grp["n_A"] > 1).mean()
    R.p()
    R.kv("matchId groups with more than one A row", fmt_pct(multi_a))
    R.kv("matchId groups with more than one DISTINCT A allocation",
         fmt_pct((grp["n_A_distinct_alloc"] > 1).mean()))

    R.check(
        "NUANCED",
        f"Genuine 1:N fan-out exists but is the minority — {fmt_pct(multi_a)} of match groups",
        "Most reconciliations are structurally simple. Note the second table: many groups "
        "with several A rows still collapse to ONE distinct allocation key, which is why the "
        "per-B answer in (a) is always 1.",
    )

    R.h3("(c) Type-B rows per matchId group — the N:1 direction")
    R.p("The reverse case: several statement entries reconciling against one ledger "
        "allocation. Each of those B rows is a separate prediction with the same answer.")
    R.block(counts_table(grp["n_B"].clip(upper=10).replace({10: "10+"}), "n_B_rows"))
    R.p()
    R.kv("matchId groups with more than one B row", fmt_pct((grp["n_B"] > 1).mean()))
    R.kv("matchId groups with zero A rows", f"{int((grp['n_A'] == 0).sum()):,}")
    R.kv("matchId groups with zero B rows", f"{int((grp['n_B'] == 0).sum()):,}")

    R.h3("(d) Joint shape of match groups")
    shape = grp.assign(
        shape=grp["n_A"].clip(upper=3).astype(str).replace({"3": "3+"}) + "A : " +
              grp["n_B"].clip(upper=3).astype(str).replace({"3": "3+"}) + "B"
    )["shape"]
    R.block(counts_table(shape, "group_shape (nA : nB)", top=20))

    R.check(
        "NUANCED",
        f"{int((grp['n_A'] == 0).sum()):,} match groups contain no A row at all",
        "These are the source of train's blank labels: a B statement entry in a group with "
        "no ledger counterpart has nothing to allocate to. Expect unmatchable B rows to exist "
        "in eval too.",
    )

    # ------------------------------------------------------------------
    R.h2("4.4 Three worked examples")

    R.p("Each example prints the type-B transaction row, then every row it is grouped with, "
        "at full width.")

    SHOW_B = ["matchId", "B_transactionType", "B_id", "B_importDate", "B_debitOrCredit",
              "B_amount", "B_valueDate", "B_currencyCode", "B_account",
              "B_transactionReferences", "B_transactionAttributes", "targetAllocation"]
    SHOW_A = ["matchId", "A_transactionType", "A_id", "A_importDate", "A_debitOrCredit",
              "A_amount", "A_valueDate", "A_currencyCode", "A_account",
              "A_transactionReferences", "A_transactionAttributes", "A_allocation"]

    def show_example(match_id, title, note):
        R.h3(title)
        R.p(note)
        R.kv("matchId", match_id)
        g = tr[tr["matchId"] == match_id]
        ga = g[g["A_transactionType"] == "A"]
        gb = g[g["B_transactionType"] == "B"]
        R.kv("group shape", f"{len(ga)} type-A row(s) : {len(gb)} type-B row(s)")
        meta = g[["matchDate", "matchRule", "matchedBy", "wasPreviouslyMismatched"]].iloc[0]
        R.kv("matchDate / matchRule / matchedBy",
             f"{meta['matchDate']} / '{meta['matchRule']}' / '{meta['matchedBy']}'")
        R.p()
        R.p("**Type-B transaction row(s) — the input, plus the label to predict:**")
        R.block(gb[SHOW_B].to_string(index=False))
        R.p()
        R.p("Target allocation(s), parsed out of the raw label string:")
        parsed_lines = []
        for _, br in gb.iterrows():
            keys = parse_alloc(br["targetAllocation"])
            parsed_lines.append(f"B_id {br['B_id']}  ->  {len(keys)} key(s)"
                                + ("  [BRACKETED SET]" if br["targetAllocation"].startswith("[")
                                   else "  [bare single key]" if keys else "  [EMPTY — no match]"))
            for i, k in enumerate(keys):
                parsed_lines.append(f"    [{i}] {k}")
        R.block("\n".join(parsed_lines))
        R.p()
        R.p("**Type-A ledger row(s) it matches to — the allocation key comes from here:**")
        if len(ga):
            R.block(ga[SHOW_A].to_string(index=False))
        else:
            R.block("<no type-A rows in this group>")
        R.p()
        a_sum = num(ga["A_amount"]).sum()
        b_sum = num(gb["B_amount"]).sum()
        R.kv("sum of A amounts", f"{a_sum:,.2f}")
        R.kv("sum of B amounts", f"{b_sum:,.2f}")
        R.kv("residual (A + B)", f"{a_sum + b_sum:,.2f}")
        R.kv("residual (A - B)", f"{a_sum - b_sum:,.2f}")

    # 1:1
    one_one = grp[(grp["n_A"] == 1) & (grp["n_B"] == 1)]
    if len(one_one):
        show_example(
            one_one.index[0],
            "Example 1 — a 1:1 case",
            "One statement entry, one ledger entry. The common case.",
        )

    # 1 B -> many A, with MORE THAN ONE DISTINCT KEY (so the label is a bracketed set)
    one_many = grp[(grp["n_A"] >= 2) & (grp["n_B"] == 1) &
                   (grp["n_A_distinct_alloc"] >= 2)].sort_values("n_A")
    if len(one_many):
        pick = (one_many[one_many["n_A"] <= 4].index[0]
                if (one_many["n_A"] <= 4).any() else one_many.index[0])
        show_example(
            pick,
            "Example 2 — one-to-many: ONE type-B transaction against MANY type-A rows, "
            "producing a MULTI-KEY target",
            "This is the case the brief is describing, in its hardest form. The A rows carry "
            "more than one distinct allocation key, so the label is the bracketed SET of them. "
            "This is the shape that breaks any code treating targetAllocation as one string.",
        )

    # 1 B -> many A that still collapse to a SINGLE key
    collapsed = grp[(grp["n_A"] >= 2) & (grp["n_B"] == 1) & (grp["n_A_distinct_alloc"] == 1)]
    if len(collapsed):
        show_example(
            collapsed.index[0],
            "Example 2b — one-to-many that COLLAPSES to a single key",
            "Same 1:N fan-out, but every A row shares one allocation key, so the label is a "
            "single bare key. This is why predicting a key is easier than predicting A_ids: "
            "the fan-out disappears into the key.",
        )

    # many B -> 1 A
    many_one = grp[(grp["n_B"] >= 2) & (grp["n_A"] == 1)].sort_values("n_B")
    if len(many_one):
        pick = many_one[many_one["n_B"] <= 4].index[0] if (many_one["n_B"] <= 4).any() else many_one.index[0]
        show_example(
            pick,
            "Example 3 — one-to-many, the other direction: MANY type-B rows against ONE type-A row",
            "Several statement entries reconcile to a single ledger allocation. Each B row is "
            "an independent prediction, and each has the same correct answer.",
        )


# ==================================================================================
# 5. BASIC STATS
# ==================================================================================
R.h1("5. Basic stats")

for base in [f for f in (TRAIN_FILE, EVAL_FILE) if f in frames_str]:
    df = frames_str[base]
    R.h2(f"File: {base}")

    a_mask = df["A_transactionType"] == "A"
    b_mask = df["B_transactionType"] == "B"

    R.h3("Date range")
    date_rows = []
    for c in ["matchDate", "A_importDate", "A_valueDate", "B_importDate", "B_valueDate"]:
        if c not in df.columns:
            continue
        s = pd.to_datetime(df[c].replace("", np.nan), errors="coerce", format="mixed")
        if s.notna().any():
            date_rows.append({
                "column": c,
                "non_null": int(s.notna().sum()),
                "min": str(s.min().date()),
                "max": str(s.max().date()),
                "span_days": int((s.max() - s.min()).days),
                "n_distinct": int(s.nunique()),
            })
        else:
            date_rows.append({"column": c, "non_null": 0, "min": "-", "max": "-",
                              "span_days": 0, "n_distinct": 0})
    R.block(pd.DataFrame(date_rows).to_string(index=False))

    R.h3("Currency distribution")
    cur = pd.concat([
        df.loc[a_mask, "A_currencyCode"].rename("currency").to_frame().assign(side="A"),
        df.loc[b_mask, "B_currencyCode"].rename("currency").to_frame().assign(side="B"),
    ])
    R.block(pd.crosstab(cur["currency"], cur["side"], margins=True, margins_name="ALL").to_string())

    R.h3("Account distribution")
    acc = pd.concat([
        df.loc[a_mask, "A_account"].rename("account").to_frame().assign(side="A"),
        df.loc[b_mask, "B_account"].rename("account").to_frame().assign(side="B"),
    ])
    ct = pd.crosstab(acc["account"], acc["side"], margins=True, margins_name="ALL")
    R.block(ct.sort_values("ALL", ascending=False).head(30).to_string())
    R.p()
    R.kv("distinct accounts", acc["account"].nunique())

    R.h3("Amount distribution")
    amt = pd.DataFrame({
        "A_amount": num(df.loc[a_mask, "A_amount"]).describe(),
        "B_amount": num(df.loc[b_mask, "B_amount"]).describe(),
    })
    extra_stats = pd.DataFrame({
        "A_amount": {
            "negative": int((num(df.loc[a_mask, "A_amount"]) < 0).sum()),
            "zero": int((num(df.loc[a_mask, "A_amount"]) == 0).sum()),
            "positive": int((num(df.loc[a_mask, "A_amount"]) > 0).sum()),
            "abs_median": float(num(df.loc[a_mask, "A_amount"]).abs().median()),
        },
        "B_amount": {
            "negative": int((num(df.loc[b_mask, "B_amount"]) < 0).sum()),
            "zero": int((num(df.loc[b_mask, "B_amount"]) == 0).sum()),
            "positive": int((num(df.loc[b_mask, "B_amount"]) > 0).sum()),
            "abs_median": float(num(df.loc[b_mask, "B_amount"]).abs().median()),
        },
    })
    R.block(pd.concat([amt, extra_stats]).to_string())

    R.p()
    R.p("Quantiles of |amount|:")
    q = pd.DataFrame({
        "A_amount_abs": num(df.loc[a_mask, "A_amount"]).abs().quantile(
            [0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99]),
        "B_amount_abs": num(df.loc[b_mask, "B_amount"]).abs().quantile(
            [0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99]),
    })
    R.block(q.to_string())

    R.h3("Debit / credit")
    dc = pd.concat([
        df.loc[a_mask, "A_debitOrCredit"].rename("dc").to_frame().assign(side="A"),
        df.loc[b_mask, "B_debitOrCredit"].rename("dc").to_frame().assign(side="B"),
    ])
    R.block(pd.crosstab(dc["dc"], dc["side"], margins=True, margins_name="ALL").to_string())

    R.p()
    R.p("Sign convention check — is the +/- sign already baked into the amount, or does "
        "`debitOrCredit` carry it?")
    sign_rows = []
    for side, mask, ac, dcc in [("A", a_mask, "A_amount", "A_debitOrCredit"),
                                ("B", b_mask, "B_amount", "B_debitOrCredit")]:
        v = num(df.loc[mask, ac])
        d = df.loc[mask, dcc]
        for tag in sorted(d.unique()):
            sel = v[d == tag]
            sign_rows.append({
                "side": side, "debitOrCredit": tag, "n": len(sel),
                "pct_negative": round(float((sel < 0).mean() * 100), 2),
                "pct_positive": round(float((sel > 0).mean() * 100), 2),
            })
    R.block(pd.DataFrame(sign_rows).to_string(index=False))


# ==================================================================================
# 6. AMOUNT RECONCILIATION
# ==================================================================================
R.h1("6. Do amounts in a one-to-many allocation sum exactly?")

if not have_train:
    R.p("Train file absent — section skipped.")
else:
    tr = frames_str[TRAIN_FILE]
    A = tr[tr["A_transactionType"] == "A"].copy()
    B = tr[tr["B_transactionType"] == "B"].copy()
    A["amt"] = num(A["A_amount"])
    B["amt"] = num(B["B_amount"])

    agg = pd.DataFrame({
        "n_A": A.groupby("matchId").size(),
        "sum_A": A.groupby("matchId")["amt"].sum(),
    }).join(pd.DataFrame({
        "n_B": B.groupby("matchId").size(),
        "sum_B": B.groupby("matchId")["amt"].sum(),
    }), how="outer")
    agg = agg[agg.index != ""]
    agg[["n_A", "n_B"]] = agg[["n_A", "n_B"]].fillna(0).astype(int)
    agg[["sum_A", "sum_B"]] = agg[["sum_A", "sum_B"]].fillna(0.0)

    both_sides = agg[(agg["n_A"] > 0) & (agg["n_B"] > 0)].copy()

    R.p("Amounts are already signed in the raw data (see the sign-convention table in "
        "section 5), so reconciliation is tested two ways and the better-fitting convention "
        "is reported rather than assumed:")
    R.p()
    R.bullet("**opposite-sign convention** — the two sides cancel: `sum_A + sum_B == 0`")
    R.bullet("**same-sign convention** — the two sides equal each other: `sum_A - sum_B == 0`")
    R.p()

    both_sides["resid_sum"] = both_sides["sum_A"] + both_sides["sum_B"]
    both_sides["resid_diff"] = both_sides["sum_A"] - both_sides["sum_B"]

    TOL = 0.005  # half a cent — "exact" at 2dp

    conv = pd.DataFrame({
        "convention": ["sum_A + sum_B == 0 (opposite sign)", "sum_A - sum_B == 0 (same sign)"],
        "groups_tested": [len(both_sides)] * 2,
        "exact_within_0.005": [
            int((both_sides["resid_sum"].abs() <= TOL).sum()),
            int((both_sides["resid_diff"].abs() <= TOL).sum()),
        ],
    })
    conv["pct_exact"] = (conv["exact_within_0.005"] / conv["groups_tested"] * 100).round(4)
    R.block(conv.to_string(index=False))

    use_diff = (both_sides["resid_diff"].abs() <= TOL).sum() >= (both_sides["resid_sum"].abs() <= TOL).sum()
    resid_col = "resid_diff" if use_diff else "resid_sum"
    conv_name = "sum_A - sum_B" if use_diff else "sum_A + sum_B"
    both_sides["residual"] = both_sides[resid_col]
    R.p()
    R.kv("convention used below", f"residual = {conv_name}")

    R.h2("6.1 Exactness by group shape")

    def shape_of(row):
        if row["n_A"] == 1 and row["n_B"] == 1:
            return "1:1"
        if row["n_A"] > 1 and row["n_B"] == 1:
            return "1 B : many A"
        if row["n_A"] == 1 and row["n_B"] > 1:
            return "many B : 1 A"
        return "many : many"

    both_sides["shape"] = both_sides.apply(shape_of, axis=1)

    tab = both_sides.groupby("shape").apply(
        lambda g: pd.Series({
            "groups": len(g),
            "exact_<=0.005": int((g["residual"].abs() <= TOL).sum()),
            "pct_exact": round(float((g["residual"].abs() <= TOL).mean() * 100), 3),
            "within_1.00": round(float((g["residual"].abs() <= 1.0).mean() * 100), 3),
            "median_abs_residual": round(float(g["residual"].abs().median()), 2),
            "p95_abs_residual": round(float(g["residual"].abs().quantile(0.95)), 2),
            "max_abs_residual": round(float(g["residual"].abs().max()), 2),
        }), include_groups=False
    )
    R.block(tab.to_string())

    R.h2("6.2 Overall answer")

    one_to_many = both_sides[both_sides["shape"] != "1:1"]
    if len(one_to_many):
        exact_otm = float((one_to_many["residual"].abs() <= TOL).mean())
        exact_11 = float((both_sides[both_sides["shape"] == "1:1"]["residual"].abs() <= TOL).mean())

        R.kv("one-to-many groups tested", f"{len(one_to_many):,}")
        R.kv("of those, amounts reconcile EXACTLY (<= 0.005)", fmt_pct(exact_otm))
        R.kv("of those, leave a residual", fmt_pct(1 - exact_otm))
        R.kv("1:1 groups reconciling exactly, for comparison", fmt_pct(exact_11))

        R.p()
        R.p("Residual magnitude on the groups that do NOT reconcile exactly:")
        nz = one_to_many[one_to_many["residual"].abs() > TOL]["residual"].abs()
        if len(nz):
            R.block(nz.describe(percentiles=[0.25, 0.5, 0.75, 0.9, 0.99]).to_string())
            R.p()
            R.p("How big is the residual relative to the transaction? "
                "(|residual| / |sum_B|, on non-exact one-to-many groups)")
            rel = (one_to_many.loc[one_to_many["residual"].abs() > TOL, "residual"].abs() /
                   one_to_many.loc[one_to_many["residual"].abs() > TOL, "sum_B"].abs().replace(0, np.nan))
            R.block(rel.describe(percentiles=[0.25, 0.5, 0.75, 0.9, 0.99]).to_string())

        R.p()
        R.p("**The aggregate number is misleading — read it by shape.** The 'many : many' "
            "bucket dominates the one-to-many population and reconciles well, which pulls the "
            "average up and hides how badly the true fan-out shapes behave:")
        R.p()
        by_shape = {}
        for shp in ["1:1", "1 B : many A", "many B : 1 A", "many : many"]:
            sel = both_sides[both_sides["shape"] == shp]
            if len(sel):
                by_shape[shp] = float((sel["residual"].abs() <= TOL).mean())
        for shp, v in by_shape.items():
            R.bullet(f"`{shp}` — {fmt_pct(v)} reconcile exactly")

        clean_shapes = [s for s, v in by_shape.items() if s != "1:1" and v < 0.5]
        R.check(
            "BROKEN",
            "Amounts in a genuine one-to-many allocation mostly do NOT sum to the transaction "
            "amount",
            f"Aggregated over all non-1:1 groups the figure looks acceptable at "
            f"{fmt_pct(exact_otm)}, but that average is carried by the 'many : many' bucket "
            f"({fmt_pct(by_shape.get('many : many', float('nan')))} exact). The shapes the "
            f"brief is actually about are far worse: '1 B : many A' reconciles exactly only "
            f"{fmt_pct(by_shape.get('1 B : many A', float('nan')))} of the time and "
            f"'many B : 1 A' only {fmt_pct(by_shape.get('many B : 1 A', float('nan')))}. "
            f"For comparison 1:1 groups are {fmt_pct(exact_11)} exact. The residuals are not "
            "rounding noise — the median non-exact residual is a five-figure amount and at the "
            "75th percentile the residual is ~37% of the transaction value. Treat amount "
            "equality as a strong signal for 1:1 and a weak one for fan-out; do not build on "
            "an assumption that a set of A rows sums to its B amount."
            + (f" Shapes failing the majority test: {clean_shapes}." if clean_shapes else ""),
        )

    R.h2("6.3 Groups with only one side present")
    only_a = int(((agg["n_A"] > 0) & (agg["n_B"] == 0)).sum())
    only_b = int(((agg["n_B"] > 0) & (agg["n_A"] == 0)).sum())
    R.kv("matchId groups with A rows only", f"{only_a:,}")
    R.kv("matchId groups with B rows only", f"{only_b:,}")
    R.kv("matchId groups with both sides", f"{len(both_sides):,}")
    R.p()
    R.p("Groups with B rows only are the unlabelled-B population identified in section 3.2.")


# ==================================================================================
# 7. SUMMARY OF ASSUMPTION CHECKS
# ==================================================================================
R.h1("7. Summary — where the brief's assumptions held and where they broke")

order = {"BROKEN": 0, "NUANCED": 1, "OK": 2}
for status in ["BROKEN", "NUANCED", "OK"]:
    items = [c for c in R.checks if c[0] == status]
    if not items:
        continue
    label = {"BROKEN": "Assumptions that BROKE", "NUANCED": "Assumptions that need NUANCE",
             "OK": "Assumptions that HELD"}[status]
    R.h2(f"{label} ({len(items)})")
    for _, title, detail in items:
        R.p(f"**{title}**")
        R.p(f"  {detail}")
        R.p()


# ==================================================================================
R.save(REPORT_PATH)
print()
print("=" * 100)
print(f"Report written to: {REPORT_PATH}")
print("=" * 100)
